name: CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'quiz-app/**'
      - 'kubernetes-manifest/**'
      
env:
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: write
  security-events: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'quiz-app/**'
            backend:
              - 'backend/**'

  build-scan-push:
    needs: changes
    runs-on: ubuntu-latest
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true'
    
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build local frontend image
        if: needs.changes.outputs.frontend == 'true'
        working-directory: ./quiz-app
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-js:${IMAGE_TAG} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-js:${IMAGE_TAG}

      - name: Trivy scan frontend Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/frontend-js:${{ env.IMAGE_TAG }}}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Push frontend image
        if: needs.changes.outputs.frontend == 'true'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-js:${IMAGE_TAG}
          
      - name: Build local backend image
        if: needs.changes.outputs.backend == 'true'
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-api:${IMAGE_TAG} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:${IMAGE_TAG}

      - name: Trivy scan backend Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/backend-api:${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Push backend image
        if: needs.changes.outputs.backend == 'true'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-api:${IMAGE_TAG}       
        
      - uses: snyk/actions/setup@master
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - run: snyk container test ${{ secrets.DOCKER_USERNAME }}/frontend-js:${IMAGE_TAG}
        if: needs.changes.outputs.frontend == 'true'
        continue-on-error: true

      - run: snyk container test ${{ secrets.DOCKER_USERNAME }}/backend-api:${IMAGE_TAG}
        if: needs.changes.outputs.backend == 'true'
        continue-on-error: true
        
      - name: Update Kubernetes manifests
        run: |
          sed -i "s|frontend-js:.*|frontend-js:${IMAGE_TAG}|" kubernetes-manifest/frontend.yaml
          sed -i "s|backend-api:.*|backend-api:${IMAGE_TAG}|" kubernetes-manifest/backend.yaml

      - name: Commit & push manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add kubernetes-manifest/
          git commit -m "Deploy ${IMAGE_TAG}" || echo "No changes"
          git push origin HEAD:refs/heads/main
